### ISSUE TITLE
Currently config module searches for 'crx.port' in the pom.xml, can we also check for 'aem.port'.

### ISSUE THREAD

**Issue by wildone** [aem-design/npm-compose-webpack#383]
## Feature Request

Currently config module searches for 'crx.port' in the pom.xml, can we also check for 'aem.port' as this is what Adobe arechtype uses now. We can check for 'aem.port' last as its more specific so would override 'crx.port' if its there.

Otherwise this error happens

`[INFO] --- frontend-maven-plugin:1.6:yarn (exec-aem-build-core) @ aglenergy-compose ---
[INFO] Running 'yarn aem:build --project core --maven --no-color' in C:\projects\agl\AGL.Digital.AEM\aglenergy-compose
[INFO] yarn run v1.22.4
[INFO] $ aemdesign-compose -p --project core --maven --no-color
[INFO] Starting up the webpack bundler...
[INFO]
[ERROR] events.js:174
[ERROR]       throw er; // Unhandled 'error' event
[ERROR]       ^
[ERROR]
[ERROR] TypeError: Cannot read property '0' of undefined
[ERROR]     at parser (C:\projects\agl\AGL.Digital.AEM\aglenergy-compose\node_modules\@aem-design\compose-webpack\dist\config.js:180:61)
[ERROR]     at C:\projects\agl\AGL.Digital.AEM\aglenergy-compose\node_modules\@aem-design\compose-webpack\dist\support\helpers.js:65:21
[ERROR]     at Parser.<anonymous> (C:\projects\agl\AGL.Digital.AEM\aglenergy-compose\node_modules\xml2js\lib\parser.js:304:18)
[ERROR]     at Parser.emit (events.js:198:13)
[ERROR]     at SAXParser.onclosetag (C:\projects\agl\AGL.Digital.AEM\aglenergy-compose\node_modules\xml2js\lib\parser.js:262:26)
[ERROR]     at emit (C:\projects\agl\AGL.Digital.AEM\aglenergy-compose\node_modules\sax\lib\sax.js:624:35)
[ERROR]     at emitNode (C:\projects\agl\AGL.Digital.AEM\aglenergy-compose\node_modules\sax\lib\sax.js:629:5)
[ERROR]     at closeTag (C:\projects\agl\AGL.Digital.AEM\aglenergy-compose\node_modules\sax\lib\sax.js:889:7)
[ERROR]     at SAXParser.write (C:\projects\agl\AGL.Digital.AEM\aglenergy-compose\node_modules\sax\lib\sax.js:1436:13)
[ERROR]     at Parser.exports.Parser.Parser.parseString (C:\projects\agl\AGL.Digital.AEM\aglenergy-compose\node_modules\xml2js\lib\parser.js:323:31)
[ERROR]     at Parser.parseString (C:\projects\agl\AGL.Digital.AEM\aglenergy-compose\node_modules\xml2js\lib\parser.js:5:59)
[ERROR]     at Object.getMavenConfigurationValueByPath (C:\projects\agl\AGL.Digital.AEM\aglenergy-compose\node_modules\@aem-design\compose-webpack\dist\support\helpers.js:60:15)
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[ERROR]     at Object.getMavenConfiguration (C:\projects\agl\AGL.Digital.AEM\aglenergy-compose\node_modules\@aem-design\compose-webpack\dist\config.js:179:31)
[ERROR]     at exports.default (C:\projects\agl\AGL.Digital.AEM\aglenergy-compose\node_modules\@aem-design\compose-webpack\dist\runtime.js:98:27)
[ERROR]     at Object.<anonymous> (C:\projects\agl\AGL.Digital.AEM\aglenergy-compose\node_modules\@aem-design\compose-webpack\dist\bin\cli-service.js:107:73)
[ERROR]     at Module._compile (internal/modules/cjs/loader.js:778:30)
[ERROR] Emitted 'error' event at:
[ERROR]     at Parser.exports.Parser.Parser.parseString (C:\projects\agl\AGL.Digital.AEM\aglenergy-compose\node_modules\xml2js\lib\parser.js:327:16)
[ERROR]     at Parser.parseString (C:\projects\agl\AGL.Digital.AEM\aglenergy-compose\node_modules\xml2js\lib\parser.js:5:59)
[ERROR]     [... lines matching original stack trace ...]
[ERROR]     at Module._compile (internal/modules/cjs/loader.js:778:30)
[ERROR]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[ERROR]     at Module.load (internal/modules/cjs/loader.js:653:32)
[ERROR]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[ERROR]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[ERROR]     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
[ERROR]     at startup (internal/bootstrap/node.js:283:19)
[ERROR]     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
[ERROR] error Command failed with exit code 1.`

**Comment by cshawaus** [comment]
Added in v2.4.0 which was just published to npm.
